
services:
  app:
    build:
      context: ./backend
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: job_app_db
      DB_USERNAME: root
      DB_PASSWORD: root

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: job_app_db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:

volumes:
  mysql-data:
