
services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: job_app_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:
